# -*- mode: ruby -*-
# vi: set ft=ruby :
#
Vagrant.require_version ">= 1.6.0"

boxes = [
    {
        :name => "dinorun",
        :eth1 => "192.168.205.111",
        :mem => "2048",
        :cpu => "2"
    }
]

Vagrant.configure(2) do |config|

  # config.vm.box = "ubuntu/xenial64"
  # config.vm.box_version = "20180510.0.0"
  config.vm.box = "jvautier/ubuntu-16.04-desktop"
  #config.vm.box = "calthorpeanalytics/ubuntu-desktop-18.04"
  #config.vm.box_version = "1.0.0"
  config.ssh.forward_agent = true

  boxes.each do |opts|
      # Set up each boxes
      config.vm.define opts[:name] do |config|
        config.vm.hostname = opts[:name]

        config.vm.provider "vmware_fusion" do |v|
          v.vmx["memsize"] = opts[:mem]
          v.vmx["numvcpus"] = opts[:cpu]
        end

        config.vm.provider "virtualbox" do |v|
          v.gui = true
          v.customize ["modifyvm", :id, "--memory", opts[:mem]]
          v.customize ["modifyvm", :id, "--cpus", opts[:cpu]]
        end

        config.vm.network :private_network, ip: opts[:eth1]
      end
  end

  config.vm.provision "file", source: "Pipfile", destination: "$HOME/"
  config.vm.provision "file", source: "../model", destination: "$HOME/model"
  config.vm.provision "shell", privileged: true, path: "./setup.sh"

  # To access a website running on port 8000, we can open a web browser
  # on our workstation and go to http://localhost:8000
  config.vm.network "forwarded_port", guest: 8000, host: 8000

  # Shared folder
  config.vm.synced_folder "tools/", "/home/vagrant/tools", create: true
end

